elasticsearch:
  build: elasticsearch
  volumes:
    - ./elasticsearch/elasticsearch.yml:/opt/elasticsearch/config/elasticsearch.yml
    - ./elasticsearch/data:/data
  environment:
    ES_HEAP_SIZE:

logstash:
  image: logstash
  command: -f /etc/logstash/conf
  links:
    - elasticsearch
  ports:
    - 6789:6789
  volumes:
    - ./logstash:/etc/logstash
  environment:
    LS_HEAP_SIZE:

kibana:
  build: kibana
  links:
    - elasticsearch
  volumes:
    - ./kibana/kibana.yml:/opt/kibana/config/kibana.yml

nginx:
  image: nginx
  links:
    - kibana
  ports:
    - 5601:5601
    - 5602:5602
  volumes:
    - ./nginx/auth.conf:/etc/nginx/sites-enabled/default
    - ./nginx/htpasswd:/etc/nginx/htpasswd

influxdb:
  image: tutum/influxdb
  ports:
    - 8083:8083
    - 8086:8086
    - 2003:2003
  volumes:
    - ./influxdb/data:/data
  environment:
    GRAPHITE_DB: graphite
    PRE_CREATE_DB: graphite
    ADMIN_USER:
    INFLUXDB_INIT_PWD:

grafana:
  image: grafana/grafana
  command: cfg:default.auth.basic.enabled=false
  ports:
    - 3000:80
  volumes:
    - ./grafana/data:/var/lib/grafana
