influxdb:
  image: tutum/influxdb
  ports:
    - 8086:8086
    - 2003:2003
  volumes:
    - ./influxdb/data:/data
  environment:
    GRAPHITE_DB: graphite
    PRE_CREATE_DB: graphite
    ADMIN_USER:
    INFLUXDB_INIT_PWD:

elasticsearch:
  build: elasticsearch
  ports:
    - 9200:9200
  volumes:
    - ./elasticsearch/elasticsearch.yml:/opt/elasticsearch/config/elasticsearch.yml
    - ./elasticsearch/data:/data
  environment:
    ES_HEAP_SIZE:

logstash:
  image: logstash
  command: -f /etc/logstash/conf
  links:
    - elasticsearch
  ports:
    - 6789:6789
  volumes:
    - ./logstash:/etc/logstash
  environment:
    LS_HEAP_SIZE:

kibana:
  image: kibana
  links:
    - elasticsearch
  environment:
    ELASTICSEARCH_URL: http://elasticsearch:9200

grafana:
  image: grafana/grafana
  command: cfg:default.users.allow_sign_up=false
  volumes:
    - ./grafana/data:/var/lib/grafana

chronograf:
  image: lukasmartinelli/chronograf
  environment:
    INFLUXDB_HOST:

nginx:
  image: nginx
  links:
    - kibana
    - grafana
    - influxdb
    - chronograf
    - elasticsearch
  ports:
    - 80:80
    - 5601:5601
    - 5602:5602
    - 5603:5603
    - 5604:5604
    - 5605:5605
  volumes:
    - ./nginx/auth.conf:/etc/nginx/conf.d/proxy.conf
    - ./nginx/htpasswd:/etc/nginx/htpasswd
