machine:
  services:
    - docker
dependencies:
  override:
    - docker build -t grafana .
    - docker run -d -p 8086:8086 -p 8084:8084 -e PRE_CREATE_DB="test" -e SSL_SUPPORT=yes tutum/influxdb
    - docker run -d -p 9200:9200 tutum/elasticsearch
    - docker run -d -p 9222:9200 -e ELASTICSEARCH_USER=admin -e ELASTICSEARCH_PASS=mypass tutum/elasticsearch
test:
  override:
    # test w/ influxdb
    - docker run -d -p 80:80 -e HTTP_PASS=mypass -e INFLUXDB_HOST=localhost -e INFLUXDB_NAME="test" grafana; sleep 5
    - curl --retry 10 --retry-delay 5 --user admin:mypass -fIL http://localhost:80/
    
    # test w/ infludb and elasticsearch
    - docker run -d -p 81:80 --name withes -e HTTP_PASS=mypass -e INFLUXDB_HOST=localhost -e INFLUXDB_NAME="test" -e ELASTICSEARCH_HOST=localhost grafana; sleep 5
    - curl --retry 10 --retry-delay 5 --user admin:mypass -fIL http://localhost:81/
    - docker logs withes | grep 'http://localhost:9200'

    # test w/ infludb and elasticsearch(authed)
    - docker run -d -p 82:80 --name withesauth -e HTTP_PASS=mypass -e INFLUXDB_HOST=localhost -e INFLUXDB_NAME="test" -e ELASTICSEARCH_HOST=localhost -e ELASTICSEARCH_PORT=9222 -e ELASTICSEARCH_USER=admin -e ELASTICSEARCH_PASS=mypass grafana; sleep 5
    - curl --retry 10 --retry-delay 5 --user admin:mypass -fIL http://localhost:82/
    - docker logs withesauth | grep 'http://admin:mypass@localhost:9222'

