#!/bin/sh

openssl genrsa -out server.key 2048
openssl req -new -key server.key -batch -out server.csr
openssl x509 -req -days 3650 -in server.csr -signkey server.key -out server.crt
rm server.csr
mv server.key logstash/
mv server.crt logstash/
